### PR TITLE
Fix sprayproxy metrics exporter

### PR DESCRIPTION
**Pull request by sayan-biswas**
## Changes
- Add service monitor and required permissions to spray proxy 
- Consolidate kube rbac proxy configs
- Merge sprayproxy and kube rbac proxy ports in one service

### CODE REVIEW

**Comment by gabemontero** [comment]
@sayan-biswas @prietyc123 @enarha so this PR brings up a staging decision with https://github.com/redhat-appstudio/sprayproxy/pull/28 as they overlap modified files.

Where we left planning was that @enarha was going to review https://github.com/redhat-appstudio/sprayproxy/pull/28 one more time and either make addition requests, or merge

But given this overlap, can you three get together and decide was is the best order to merge the PRs.  Also, I have not looked in detail, but see if the changes conflict somehow, or if one PR renders the other PR redundant.

**Comment by sayan-biswas** [comment]
@gabemontero Yes there are few overlapping changes, I'll have a discussion with @prietyc123 tomorrow.

**Comment by sayan-biswas** [comment]
Rebased to the latest changes.

**Pull request merged**
