### PR TITLE
Fix sprayproxy service

### PR DESCRIPTION
**Pull request by sayan-biswas**
Fix sprayproxy service to route traffic through kube-rbac container.

### CODE REVIEW

**Comment by enarha** [comment]
/lgtm
We can merge this and try to propagate to infra-deployments before the revert change, but if it does not help, it'll conflict with the revert change. The other option is to finish with revert, get this change tested locally and only then push forward to infra-deployments. WDYT?

**Comment by sayan-biswas** [comment]
@enarha Did you get a chance to test this?

**Comment by enarha** [comment]
I was able to test and successfully verify the fix.

**Pull request merged**
