### PR TITLE
Fix server command flags parsing

### PR DESCRIPTION
**Pull request by enarha**
Fix backend flags parsing typo, so backends are actually used.

### CODE REVIEW

**Review by gabemontero — APPROVED** [review]

**Comment by gabemontero** [comment]
I can hit the merge button @adambkaplan unless you want to double check

**Review by adambkaplan — CHANGES_REQUESTED** [review]
Please also update the environment variable name in `config/sprayproxy.yaml`, as well as the README.md. I don't think we will need a corresponding change in infra-deployments, since that uses a raw json patch to add the backends in the staging environment.

See https://github.com/redhat-appstudio/infra-deployments/blob/multi-cluster/components/sprayproxy/add-backends.yml

**Comment by enarha** [comment]
Updated.

**Comment by gabemontero** [comment]
> Please also update the environment variable name in `config/sprayproxy.yaml`, as well as the README.md. I don't think we will need a corresponding change in infra-deployments, since that uses a raw json patch to add the backends in the staging environment.
> 
> See https://github.com/redhat-appstudio/infra-deployments/blob/multi-cluster/components/sprayproxy/add-backends.yml

ah right the env vars .... still a go-gonic newbie :-)

**Review by adambkaplan — APPROVED** [review]
/approve

/lgtm

We're at the point where we need e2e testing of the proxy that runs against infra-deployments.

**Pull request merged**
