### PR TITLE
Measure Test Code Coverage

### PR DESCRIPTION
**Pull request by xinredhat**

### CODE REVIEW

**Comment by enarha** [comment]
I thought we are going to see the result as a comment on the PR instead of having to go to a 3rd party website. Is that possible?

**Comment by xinredhat** [comment]
> I thought we are going to see the result as a comment on the PR instead of having to go to a 3rd party website. Is that possible?

yes, it should show up the result as a comment on the PR. let me double check if it's expected request for this PR

**Comment by xinredhat** [comment]
@enarha could you help check if Codecov Github app is installed on this repo. It should have the comment like this https://github.com/xinredhat/sprayproxy/pull/1#issuecomment-1717374488

**Comment by enarha** [comment]
I do not have permissions to check apps on the repo.

**Comment by xinredhat** [comment]
@enarha I don't quite understand why it didn't show up the result data as comments in this PR. Actually the coverage data is uploaded to Codecov https://app.codecov.io/gh/redhat-appstudio/sprayproxy

**Pull request merged**
